"use client";
import { useEffect,useState } from "react";
import type { Task } from "@/lib/domain";
type ReminderTask=Task & { reminderMinutes?:number; description?:string|null };

const recurrence=["none","daily","weekly","monthly","monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
const priorities=["low","medium","high"];

export default function TasksPage(){
 const [tasks,setTasks]=useState<ReminderTask[]>([]); const [selectedId,setSelectedId]=useState<string|null>(null); const [notificationState,setNotificationState]=useState<"unknown"|"granted"|"denied">("unknown"); const [notified,setNotified]=useState<string[]>([]);
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[date,setDate]=useState(()=>{const d=new Date();return d.toISOString().slice(0,10)}),[time,setTime]=useState("09:00"),[duration,setDuration]=useState("30"),[priority,setPriority]=useState("medium"),[project,setProject]=useState(""),[repeat,setRepeat]=useState("none"),[reminder,setReminder]=useState("10");
 useEffect(()=>{fetch("/api/db?type=tasks").then(r=>r.json()).then(setTasks); const id=new URLSearchParams(window.location.search).get("task"); if(id)setSelectedId(id)},[]);
 useEffect(()=>{if("Notification" in window)setNotificationState(Notification.permission as "granted"|"denied"|"unknown"); if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{});},[]);
 useEffect(()=>{if(notificationState!=="granted")return; const check=()=>{const now=new Date();tasks.filter(t=>t.status!=="done").forEach(t=>{const [h,m]=String(t.time||"09:00").split(":").map(Number);const when=new Date(t.date);when.setHours(h||0,m||0,0,0);const lead=(t.reminderMinutes??10)*60000;const key=t.id+":"+t.date+":"+t.time;if(now.getTime()>=when.getTime()-lead&&now.getTime()<when.getTime()+Math.max(t.duration||30,1)*60000&&!notified.includes(key)){new Notification(t.title,{body:(t.reminderMinutes??10)===0?"Starting now":"Starts in "+(t.reminderMinutes??10)+" minutes",tag:key,data:{url:"/tasks?task="+t.id}});setNotified(v=>[...v,key]);}})};check();const id=window.setInterval(check,30000);return()=>window.clearInterval(id)},[tasks,notificationState,notified]);
 async function enableNotifications(){if(!("Notification" in window)){setNotificationState("denied");return}const p=await Notification.requestPermission();setNotificationState(p as "granted"|"denied")}
 async function create(){
  if(!title.trim())return;
  const x=await fetch("/api/db",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"task",title,description,date,time,duration:Number(duration),priority,project,recurrence:repeat,reminderMinutes:Number(reminder)})}).then(r=>r.json());
  setTasks(v=>[...v,x]);setTitle("");setDescription("");
 }
 async function toggle(task:Task){const status=task.status==="done"?"todo":"done";const x=await fetch("/api/db",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"task",id:task.id,status})}).then(r=>r.json());setTasks(v=>v.map(t=>t.id===x.id?x:t)); setSelectedId(null)}
 async function update(task:Task,patch:any){const x=await fetch("/api/db",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"task",id:task.id,...patch})}).then(r=>r.json());setTasks(v=>v.map(t=>t.id===x.id?x:t))}
 async function updateSeries(task:Task,patch:any){const x=await fetch("/api/db",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"task",id:task.id,seriesEdit:true,...patch})}).then(r=>r.json());setTasks(v=>v.map(t=>t.recurrenceKey===task.recurrenceKey?{...t,...patch}:t))}
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">EXECUTION ENGINE</p><h1>Tasks</h1><p>Schedule work precisely, repeat what matters, and keep execution connected to the rest of NEXUM.</p></div><span className="module-count">{tasks.filter(t=>t.status==="done").length}/{tasks.length} done</span></header>
 <section className="notification-bar"><div><p className="eyebrow">REMINDERS</p><strong>{notificationState==="granted"?"Browser reminders are enabled.":"Enable browser reminders to receive task alerts while NEXUM is open."}</strong></div>{notificationState!=="granted"&&<button className="text-button" onClick={enableNotifications}>Enable reminders</button>}</section><section className="task-create"><div className="task-create-main"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs to happen?"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description or definition of done"/></div><div className="task-fields"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}><option>15</option><option>30</option><option>45</option><option>60</option><option>90</option><option>120</option></select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(x=><option key={x}>{x}</option>)}</select></label><label>Repeat<select value={repeat} onChange={e=>setRepeat(e.target.value)}>{recurrence.map(x=><option key={x}>{x}</option>)}</select></label><label>Reminder<select value={reminder} onChange={e=>setReminder(e.target.value)}><option value="0">At time</option><option value="5">5 min before</option><option value="10">10 min before</option><option value="15">15 min before</option><option value="30">30 min before</option><option value="60">1 hour before</option></select></label><label>Project<input value={project} onChange={e=>setProject(e.target.value)} placeholder="Optional"/></label></div><button className="primary-button" onClick={create}>Schedule task</button></section>
 <section className="task-list">{tasks.map(task=><article id={"task-"+task.id} className={(task.status==="done"?"task-row is-done ":"task-row ")+(selectedId===task.id?"task-selected":"")} key={task.id}><button className="check-button" onClick={()=>toggle(task)}>{task.status==="done"?"✓":""}</button><div className="task-main"><h2>{task.title}</h2><p>{task.date?.slice(0,10)} · {task.time} · {task.duration} min{task.project?" · "+task.project:""}{task.recurrence&&task.recurrence!=="none"?" · repeats "+task.recurrence:""}</p>{task.description&&<small>{task.description}</small>}{task.reminderMinutes!==undefined&&<small>Reminder: {task.reminderMinutes===0?"at time":task.reminderMinutes+" min before"}</small>}</div><div className="task-actions">{task.recurrence&&task.recurrence!=="none"&&<><button className="text-button" onClick={()=>update(task,{recurrence:"none",recurrenceRule:null})}>Make one-time</button><button className="text-button" onClick={()=>updateSeries(task,{priority:task.priority})}>Edit series</button></>}<select className={"priority-select "+task.priority} value={task.priority} onChange={e=>update(task,{priority:e.target.value})}>{priorities.map(x=><option key={x}>{x}</option>)}</select></div></article>)}</section></main>
}