"use client";
import { useEffect,useState } from "react";
type LinkRow={id:string;fromType:string;fromId:string;toType:string;toId:string;relation:string};
type Entry={id:string;title:string;type:string;topic:string;tags:string;content:string};
export default function KnowledgePage(){
 const [entries,setEntries]=useState<Entry[]>([]),[query,setQuery]=useState(""),[selected,setSelected]=useState<Entry|null>(null),[links,setLinks]=useState<LinkRow[]>([]),[target,setTarget]=useState(""),[relation,setRelation]=useState("relates to");
 useEffect(()=>{fetch("/api/db?type=knowledge").then(r=>r.json()).then(setEntries)},[]);
 async function open(e:Entry){setSelected(e);const r=await fetch("/api/links?fromType=knowledge&fromId="+e.id);setLinks(await r.json())}
 async function connect(){if(!selected||!target)return;const t=entries.find(x=>x.id===target);const r=await fetch("/api/links",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fromType:"knowledge",fromId:selected.id,toType:"knowledge",toId:target,relation})});if(r.ok)setLinks(v=>[...v,await r.json()]);}
 const filtered=entries.filter(e=>[e.title,e.topic,e.content,e.tags].join(" ").toLowerCase().includes(query.toLowerCase()));
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">ARCHIVE</p><h1>Knowledge</h1><p>Your persistent notes, sources, ideas, insights, and questions.</p></div><span className="module-count">{entries.length} entries</span></header><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search knowledge..."/></div><section className="knowledge-grid">{filtered.map(e=><article className="knowledge-card" key={e.id} onClick={()=>open(e)}><div className="card-meta"><span>{e.type}</span><span>{e.topic}</span></div><h2>{e.title}</h2><p>{e.content}</p><div className="tag-row">{e.tags.split(",").filter(Boolean).map(t=><span key={t}>{t}</span>)}</div></article>)}</section>{selected&&<aside className="relationship-panel"><div className="card-meta"><span>RELATIONSHIPS</span><button className="text-button" onClick={()=>setSelected(null)}>Close</button></div><h2>{selected.title}</h2><div className="relationship-form"><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Connect to…</option>{entries.filter(e=>e.id!==selected.id).map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><select value={relation} onChange={e=>setRelation(e.target.value)}><option>relates to</option><option>supports</option><option>contradicts</option><option>extends</option><option>inspired</option></select><button className="primary-button" onClick={connect}>Connect</button></div>{links.map(l=><div className="relationship-row" key={l.id}><span>{l.relation}</span><b>{entries.find(e=>e.id===l.toId)?.title||l.toId}</b></div>)}{!links.length&&<p className="empty-state">No explicit relationships yet.</p>}</aside>}</main>
}