import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
const TYPES = new Set(["knowledge", "research", "library", "content", "project"]);
const RELATIONS = new Set(["relates to", "supports", "contradicts", "extends", "derived from", "cites", "inspired", "informs", "produces", "belongs to"]);
function value(v: unknown) { return typeof v === "string" ? v.trim() : ""; }
function validLink(b: any) { const fromType=value(b.fromType),fromId=value(b.fromId),toType=value(b.toType),toId=value(b.toId),relation=value(b.relation); if (!fromType||!fromId||!toType||!toId||!relation||!TYPES.has(fromType)||!TYPES.has(toType)||!RELATIONS.has(relation)||fromId.length>100||toId.length>100) return null; return {fromType,fromId,toType,toId,relation}; }
async function exists(type:string,id:string){const map:any={knowledge:db.knowledgeEntry,research:db.researchProject,library:db.libraryFile,content:db.contentItem,project:db.project};return Boolean(await map[type].findUnique({where:{id},select:{id:true}}));}
export async function GET(request:NextRequest){try{const p=request.nextUrl.searchParams,where:any={};for(const k of ["fromType","toType"]){const v=p.get(k);if(v&&!TYPES.has(v))return NextResponse.json({error:"Invalid relationship type."},{status:400});if(v)where[k]=v;}for(const k of ["fromId","toId"]){const v=p.get(k);if(v&&v.length>100)return NextResponse.json({error:"Relationship identifier is too long."},{status:400});if(v)where[k]=v;}return NextResponse.json(await db.knowledgeLink.findMany({where,orderBy:{createdAt:"desc"}}));}catch{return NextResponse.json({error:"Unable to load relationships."},{status:500});}}
export async function POST(request:NextRequest){try{const link=validLink(await request.json());if(!link)return NextResponse.json({error:"Invalid relationship fields."},{status:400});if(!(await exists(link.fromType,link.fromId))||!(await exists(link.toType,link.toId)))return NextResponse.json({error:"Both relationship targets must exist."},{status:404});return NextResponse.json(await db.knowledgeLink.upsert({where:{fromType_fromId_toType_toId_relation:link},update:{},create:link}));}catch{return NextResponse.json({error:"Unable to create relationship."},{status:500});}}
export async function DELETE(request:NextRequest){try{const link=validLink(await request.json());if(!link)return NextResponse.json({error:"Invalid relationship fields."},{status:400});await db.knowledgeLink.deleteMany({where:link});return NextResponse.json({deleted:true});}catch{return NextResponse.json({error:"Unable to delete relationship."},{status:500});}}