"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Task={id:string;title:string;time:string;duration:number;status:string;priority:string;project?:string|null;date:string};
type Knowledge={id:string;title:string;type:string;topic:string};
type Project={id:string;name:string;progress:number;status:string};
type Inbox={id:string;text:string;status:string};
type Suggestion={kind:string;priority:"high"|"medium"|"low";title:string;reason:string;action:string;entityType?:string;entityId?:string};

const nav=[["Dashboard","/"],["Inbox","/inbox"],["Knowledge","/knowledge"],["Research","/research"],["Connections","/connections"],["Projects","/projects"],["Content","/content"],["Tasks","/tasks"],["Journal","/journal"],["Library","/library"],["Search","/search"],["Insights","/insights"],["AI","/ai"]];

export default function Home(){
 const [tasks,setTasks]=useState<Task[]>([]),[pendingCommand,setPendingCommand]=useState<any>(null),[knowledge,setKnowledge]=useState<Knowledge[]>([]),[projects,setProjects]=useState<Project[]>([]),[inbox,setInbox]=useState<Inbox[]>([]),[automation,setAutomation]=useState<Suggestion[]>([]),[command,setCommand]=useState(""),[commandResult,setCommandResult]=useState<any>(null),[commanding,setCommanding]=useState(false);
 useEffect(()=>{Promise.all([fetch("/api/db?type=tasks").then(r=>r.json()),fetch("/api/db?type=knowledge").then(r=>r.json()),fetch("/api/db?type=projects").then(r=>r.json()),fetch("/api/db?type=inbox").then(r=>r.json()),fetch("/api/automation").then(r=>r.json())]).then(([t,k,p,i,a])=>{setTasks(t);setKnowledge(k);setProjects(p);setInbox(i);setAutomation(a.suggestions||[]);});},[]);
 const todayKey=new Date().toISOString().slice(0,10); const today=useMemo(()=>tasks.filter(t=>t.date?.slice(0,10)===todayKey),[tasks,todayKey]);
 async function runCommand(){if(!command.trim())return;setCommanding(true);const r=await fetch("/api/command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command})});const d=await r.json();setCommandResult(d);setPendingCommand(d.type==="confirmation_required"?d:null);setCommanding(false)}
 const now=new Date(),hour=now.getHours(),greeting=hour<12?"Good morning.":hour<18?"Good afternoon.":"Good evening.";
 const dateLabel=new Intl.DateTimeFormat("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(now).toUpperCase();
 return <main className="shell"><aside className="sidebar"><div className="brand">NEXUM</div><nav>{nav.map(([x,href],i)=><Link className={i===0?"nav active":"nav"} href={href} key={x}>{x}</Link>)}</nav><div className="sideFoot">PRIVATE WORKSPACE<br/><span>Personal archive</span></div></aside>
 <section className="content"><header className="top"><div><p className="eyebrow">{dateLabel}</p><h1>{greeting}</h1></div><div className="avatar">H</div></header>
 <section className="panel command-panel"><p className="eyebrow">COMMAND</p><h2>Tell NEXUM what you need.</h2><div className="command-row"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")runCommand()}} placeholder="Search, or type task: / note: / research:"/><button className="primary-button" onClick={runCommand} disabled={commanding}>{commanding?"Working…":"Run"}</button></div>{commandResult?.type==="search"&&<div className="command-results">{commandResult.results.map((x:any)=><div className="insight-row" key={x.kind+x.id}><strong>{x.title}</strong><span>{x.kind}{x.score?` · ${Math.round(x.score*100)}%`:""}</span></div>)}{commandResult.connections?.length>0&&<div className="command-connections"><p className="eyebrow">CONNECTED CONTEXT</p>{commandResult.connections.slice(0,8).map((x:any)=><div className="insight-row" key={x.id}><strong>{x.fromType} → {x.toType}</strong><span>{x.relation}</span></div>)}</div>}</div>}{commandResult?.type==="created"&&<div className="empty-state">Created {commandResult.kind}: {commandResult.item.title}</div>}</section>{pendingCommand&&<section className="panel command-confirm"><p className="eyebrow">CONFIRM ACTION</p><h2>{pendingCommand.title}</h2><p>{pendingCommand.schedule}</p><div className="command-actions"><button className="primary-button" onClick={async()=>{setCommanding(true);const r=await fetch("/api/command",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({command:pendingCommand.command,confirm:true})});const d=await r.json();setCommandResult(d);setPendingCommand(null);setCommanding(false)}} disabled={commanding}>{commanding?"Creating…":"Confirm & Create"}</button><button onClick={()=>setPendingCommand(null)} disabled={commanding}>Cancel</button></div></section>}<section className="grid"><div className="panel"><div className="head"><div><p className="eyebrow">TODAY</p><h2>Schedule</h2></div><Link className="link" href="/tasks">View all</Link></div><div className="tasks">{today.map(t=><div className={t.status==="done"?"task done":"task"} key={t.id}><time>{t.time}</time><div><strong>{t.title}</strong><span>{t.duration} min · {t.priority}{t.project?" · "+t.project:""}</span></div><span className="status-dot">{t.status==="done"?"✓":"○"}</span></div>)}{!today.length&&<div className="empty-state">No tasks scheduled for today.</div>}</div></div>
 <div className="panel"><div className="head"><div><p className="eyebrow">SYSTEM PULSE</p><h2>What needs attention</h2></div><Link className="link" href="/insights">Open insights</Link></div>{automation.slice(0,4).map(x=><div className="insight-row" key={x.kind+x.entityId}><strong>{x.title}</strong><span>{x.priority}</span></div>)}{!automation.length&&<div className="empty-state">No stale or overdue signals.</div>}</div></section>
 <section className="grid lower"><div className="panel capture"><p className="eyebrow">QUICK CAPTURE</p><h2>Put it in NEXUM.</h2><p>{inbox.length?"You have "+inbox.length+" items waiting to be organized.":"Save a thought, source, link, question, or idea before you lose it."}</p><Link className="primary" href="/inbox">Open inbox</Link></div><div className="panel"><p className="eyebrow">ACTIVE WORK</p><h2>Current projects</h2>{projects.slice(0,3).map(p=><div className="thread" key={p.id}><b>{String(p.progress).padStart(2,"0")}</b><div><strong>{p.name}</strong><p>{p.progress}% complete · {p.status}</p></div></div>)}{!projects.length&&<div className="empty-state">No projects yet.</div>}</div></section>
 <section className="grid lower"><div className="panel"><div className="head"><div><p className="eyebrow">KNOWLEDGE</p><h2>Recent archive</h2></div><Link className="link" href="/knowledge">Open library</Link></div>{knowledge.slice(0,5).map(k=><div className="insight-row" key={k.id}><strong>{k.title}</strong><span>{k.topic}</span></div>)}{!knowledge.length&&<div className="empty-state">Your archive is empty.</div>}</div><div className="panel"><p className="eyebrow">EXECUTION</p><h2>{tasks.filter(t=>t.status==="done").length} completed tasks</h2><p className="muted">{tasks.filter(t=>t.status!=="done").length} tasks remain open across your schedule.</p><Link className="link" href="/tasks">Open execution engine</Link></div></section>
 </section></main>;
}