"use client";
import {useEffect,useState} from "react";

type Suggestion={kind:string;priority:"high"|"medium"|"low";title:string;reason:string;action:string;entityType?:string;entityId?:string};

export default function InsightsPage(){
 const [d,setD]=useState<any>(null),[automation,setAutomation]=useState<Suggestion[]>([]),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const [a,b]=await Promise.all([fetch("/api/insights").then(r=>r.json()),fetch("/api/automation").then(r=>r.json())]);setD(a);setAutomation(b.suggestions||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 if(!d)return <main className="module-page"><p>Loading intelligence…</p></main>;
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">LONG-TERM INTELLIGENCE</p><h1>Insights</h1><p>See what is accumulating, unfinished, and emerging across NEXUM.</p></div></header>
 <section className="insight-grid">{Object.entries(d.overview).map(([k,v])=><div className="insight-stat" key={k}><b>{String(v)}</b><span>{k}</span></div>)}</section>
 <section className="insight-panels"><article className="panel automation-panel"><div className="section-head"><div><p className="eyebrow">AUTOMATION CENTER</p><h2>What needs attention</h2></div><button onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>{automation.length===0?<p className="muted">Nothing is currently stale or overdue.</p>:automation.map((x,i)=><div className="automation-row" key={x.kind+x.entityId+i}><div><span className={"priority priority-"+x.priority}>{x.priority}</span><strong>{x.title}</strong><p>{x.reason}</p><small>{x.action}</small></div><button onClick={()=>{if(x.entityType==="task")window.location.href="/tasks?task="+x.entityId;else if(x.entityType==="research")window.location.href="/research";else if(x.entityType==="content")window.location.href="/content";else if(x.entityType==="project")window.location.href="/projects";else if(x.entityType==="inbox")window.location.href="/inbox"}}>Open</button></div>)}</article>
 <article className="panel"><p className="eyebrow">UNFINISHED RESEARCH</p>{d.unfinished.research.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>{x.status}</span></div>)}</article><article className="panel"><p className="eyebrow">OPEN TASKS</p>{d.unfinished.tasks.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>{x.priority}</span></div>)}</article><article className="panel"><p className="eyebrow">JOURNAL SIGNALS</p>{d.patterns.map((x:any)=><div className="insight-row" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</article><article className="panel"><p className="eyebrow">CONTENT IDEAS</p>{d.unfinished.content.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>idea</span></div>)}</article></section></main>
}