"use client";
import {useEffect,useState} from "react";

type Suggestion={kind:string;priority:"high"|"medium"|"low";title:string;reason:string;action:string;entityType?:string;entityId?:string};

export default function InsightsPage(){
 const [d,setD]=useState<any>(null),[automation,setAutomation]=useState<Suggestion[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState<string>("");
 async function load(){setLoading(true);const [a,b]=await Promise.all([fetch("/api/insights").then(r=>r.json()),fetch("/api/automation").then(r=>r.json())]);setD(a);setAutomation(b.suggestions||[]);setLoading(false)}
 async function execute(x:Suggestion,action:string){if(!x.entityId)return;const key=x.kind+x.entityId+action;setBusy(key);const res=await fetch("/api/automation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:x.kind,entityId:x.entityId,action})});if(res.ok)await load();else alert((await res.json()).error||"Action failed.");setBusy("")}
 useEffect(()=>{load()},[]);
 if(!d)return <main className="module-page"><p>Loading intelligence…</p></main>;
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">LONG-TERM INTELLIGENCE</p><h1>Insights</h1><p>See what is accumulating, unfinished, and emerging across NEXUM.</p></div></header>
 <section className="insight-grid">{Object.entries(d.overview).map(([k,v])=><div className="insight-stat" key={k}><b>{String(v)}</b><span>{k}</span></div>)}</section>
 <section className="insight-panels"><article className="panel automation-panel"><div className="section-head"><div><p className="eyebrow">AUTOMATION CENTER</p><h2>What needs attention</h2></div><button onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>{automation.length===0?<p className="muted">Nothing is currently stale or overdue.</p>:automation.map((x,i)=><div className="automation-row" key={x.kind+x.entityId+i}><div><span className={"priority priority-"+x.priority}>{x.priority}</span><strong>{x.title}</strong><p>{x.reason}</p><small>{x.action}</small></div><div className="automation-actions">{x.kind==="overdue-task"&&<><button onClick={()=>execute(x,"complete")} disabled={!!busy}>Complete</button><button onClick={()=>{const date=window.prompt("Reschedule date (YYYY-MM-DD)");if(date)execute(x,"reschedule")}} disabled={!!busy}>Reschedule</button></>}{x.kind==="stale-inbox"&&<><button onClick={()=>execute(x,"complete")} disabled={!!busy}>Process</button><button onClick={()=>execute(x,"archive")} disabled={!!busy}>Archive</button></>}{x.kind==="stale-content-idea"&&<><button onClick={()=>execute(x,"publish")} disabled={!!busy}>Publish</button><button onClick={()=>execute(x,"archive")} disabled={!!busy}>Archive</button></>}{x.entityType==="research"&&<button onClick={()=>window.location.href="/research"}>Open</button>}{x.entityType==="project"&&<button onClick={()=>window.location.href="/projects"}>Open</button>}</div></div>)}</article>
 <article className="panel"><p className="eyebrow">UNFINISHED RESEARCH</p>{d.unfinished.research.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>{x.status}</span></div>)}</article><article className="panel"><p className="eyebrow">OPEN TASKS</p>{d.unfinished.tasks.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>{x.priority}</span></div>)}</article><article className="panel"><p className="eyebrow">JOURNAL SIGNALS</p>{d.patterns.map((x:any)=><div className="insight-row" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</article><article className="panel"><p className="eyebrow">CONTENT IDEAS</p>{d.unfinished.content.map((x:any)=><div className="insight-row" key={x.id}><strong>{x.title}</strong><span>idea</span></div>)}</article></section></main>
}