"use client";

import { FormEvent, useState } from "react";

const prompts = ["What have I learned recently?","What research threads look unfinished?","Find connections between my knowledge.","What should I investigate next?","What research could become content?"];

export default function AIPage() {
 const [question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[loading,setLoading]=useState(false),[actionLoading,setActionLoading]=useState(""),[sources,setSources]=useState<any[]>([]);
 async function ask(event?:FormEvent){event?.preventDefault();if(!question.trim())return;setLoading(true);setAnswer("");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});const d=await r.json();setAnswer(d.answer||d.error||"No response.");setSources(d.sources||[])}catch{setAnswer("NEXUM could not reach the AI service.")}finally{setLoading(false)}}
 async function action(kind:string){setActionLoading(kind);try{const payload=kind==="task"?{action:"create-task",title:question||"Follow up on NEXUM insight",description:answer}:kind==="research"?{action:"create-research",title:question.slice(0,80)||"New research thread",question}: {action:"create-content",title:question.slice(0,80)||"New content idea",sourceIdea:answer};const r=await fetch("/api/ai/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setAnswer(answer+"\n\nCreated in NEXUM: "+(d.title||d.name||"new item"));}finally{setActionLoading("")}}
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">NEXUM INTELLIGENCE</p><h1>Ask your archive.</h1><p>Search, synthesize, connect, then turn an insight into work.</p></div></header><section className="ai-workspace"><form onSubmit={ask} className="ai-form"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What do you want NEXUM to find, explain, connect, or surface?"/><button className="primary-button" disabled={loading}>{loading?"Thinking...":"Ask NEXUM"}</button></form><div className="prompt-row">{prompts.map(p=><button key={p} type="button" onClick={()=>setQuestion(p)}>{p}</button>)}</div>{answer&&<article className="ai-answer"><span className="row-label">NEXUM INTELLIGENCE</span><div>{answer}</div>{sources.length>0&&<div className="ai-sources"><span className="row-label">RETRIEVED RECORDS</span>{sources.slice(0,8).map((s:any)=><div key={String(s.index)+s.title}>[{s.index}] {s.kind} · {s.title}</div>)}</div>}<div className="ai-actions"><button onClick={()=>action("task")} disabled={!!actionLoading}>{actionLoading==="task"?"Creating…":"Turn into task"}</button><button onClick={()=>action("research")} disabled={!!actionLoading}>{actionLoading==="research"?"Creating…":"Start research"}</button><button onClick={()=>action("content")} disabled={!!actionLoading}>{actionLoading==="content"?"Creating…":"Create content idea"}</button></div></article>}</section></main>;
}