"use client";
import { useEffect,useState } from "react";
type Source={id:string;title:string;url:string;notes:string}; type Research={id:string;title:string;question:string;status:string;notes:string;insights:string;sources:Source[]};
const statuses=["idea","researching","analyzing","ready","archived"];
export default function ResearchPage(){
 const [items,setItems]=useState<Research[]>([]),[selected,setSelected]=useState<Research|null>(null),[title,setTitle]=useState(""),[question,setQuestion]=useState(""),[notes,setNotes]=useState(""),[insights,setInsights]=useState(""),[sourceTitle,setSourceTitle]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/research").then(r=>r.json()).then(setItems)},[]);
 async function create(){if(!title.trim())return;const item=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,question})}).then(r=>r.json());setItems(v=>[item,...v]);setTitle("");setQuestion("");setSelected(item)}
 function open(item:Research){setSelected(item);setNotes(item.notes||"");setInsights(item.insights||"");}
 async function save(){if(!selected)return;const updated=await fetch("/api/research",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,status:selected.status,notes,insights})}).then(r=>r.json());setItems(v=>v.map(x=>x.id===updated.id?updated:x));setSelected(updated);setMessage("Research thread updated.")}
 async function advance(item:Research){const next=statuses[Math.min(statuses.indexOf(item.status)+1,statuses.length-1)];const updated=await fetch("/api/research",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status:next,notes:item.notes,insights:item.insights})}).then(r=>r.json());setItems(v=>v.map(x=>x.id===updated.id?updated:x));if(selected?.id===item.id)setSelected(updated)}
 async function addSource(){if(!selected||!sourceTitle.trim()||!sourceUrl.trim())return;const source=await fetch("/api/research/source",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:selected.id,title:sourceTitle,url:sourceUrl})}).then(r=>r.json());const updated={...selected,sources:[...selected.sources,source]};setSelected(updated);setItems(v=>v.map(x=>x.id===updated.id?updated:x));setSourceTitle("");setSourceUrl("");setMessage("Source added.")}
 return <main className="module-page"><header className="module-header"><div><p className="eyebrow">RESEARCH WORKSPACE</p><h1>Research</h1><p>Move a question from idea to evidence, insight, and publishable opportunity.</p></div><span className="module-count">{items.length} threads</span></header>
 <section className="capture-form project-create"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Research title"/><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Research question"/><button className="primary-button" onClick={create}>Start research</button></section>
 <section className="research-list">{items.map(item=><article className="research-card" key={item.id} onClick={()=>open(item)}><div className="card-meta"><span>{item.status}</span><span>{item.sources.length} sources</span></div><h2>{item.title}</h2><p className="research-question">{item.question||"No research question defined."}</p><div className="research-flow">{statuses.map(s=><span className={s===item.status?"active":""} key={s}>{s}</span>)}</div><button className="text-button" onClick={e=>{e.stopPropagation();advance(item)}}>{item.status==="archived"?"Archived":"Move to "+statuses[Math.min(statuses.indexOf(item.status)+1,statuses.length-1)]}</button></article>)}</section>
 {selected&&<aside className="research-workspace"><div className="card-meta"><span>RESEARCH THREAD</span><button className="text-button" onClick={()=>setSelected(null)}>Close</button></div><h2>{selected.title}</h2><p className="research-question">{selected.question}</p><div className="research-flow">{statuses.map(s=><span className={s===selected.status?"active":""} key={s}>{s}</span>)}</div><label className="workspace-label">Evidence & notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Facts, sources, observations, uncertainty."/></label><label className="workspace-label">Insights<textarea value={insights} onChange={e=>setInsights(e.target.value)} placeholder="Conclusions, patterns, contradictions, implications."/></label><button className="primary-button" onClick={save}>Save research</button><section className="source-section"><div className="card-meta"><span>SOURCES</span><span>{selected.sources.length}</span></div>{selected.sources.map(s=><div className="source-row" key={s.id}><div><b>{s.title}</b><a href={s.url} target="_blank" rel="noreferrer">{s.url}</a></div></div>)}<div className="source-add"><input value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)} placeholder="Source title"/><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://..."/><button className="text-button" onClick={addSource}>Add source</button></div></section>{message&&<small>{message}</small>}</aside>}
 </main>
}