import { NextRequest, NextResponse } from "next/server";
import webpush from "web-push";
import { db } from "@/lib/db";
export async function POST(request:NextRequest){
 const secret=request.headers.get("x-nexum-cron-secret"); if(process.env.NEXUM_CRON_SECRET&&secret!==process.env.NEXUM_CRON_SECRET)return NextResponse.json({error:"Unauthorized."},{status:401});
 if(!process.env.VAPID_PUBLIC_KEY||!process.env.VAPID_PRIVATE_KEY||!process.env.VAPID_SUBJECT)return NextResponse.json({error:"VAPID configuration is missing."},{status:503});
 webpush.setVapidDetails(process.env.VAPID_SUBJECT,process.env.VAPID_PUBLIC_KEY,process.env.VAPID_PRIVATE_KEY);
 const recurringResponse=await fetch(new URL("/api/automation",request.url),{method:"POST",headers:{"x-nexum-action":"generate-recurring"}}); if(!recurringResponse.ok)return NextResponse.json({error:"Recurring task generation failed."},{status:500}); const now=new Date(),end=new Date(now.getTime()+65*60000); const tasks=await db.task.findMany({where:{status:{not:"done"},date:{gte:new Date(now.getFullYear(),now.getMonth(),now.getDate()),lte:end}}}); const subs=await db.pushSubscription.findMany(); let sent=0;
 for(const task of tasks){const parts=String(task.time||"09:00").split(":").map(Number);const when=new Date(task.date);when.setHours(parts[0]||0,parts[1]||0,0,0);const fireAt=new Date(when.getTime()-(task.reminderMinutes||0)*60000);if(now<fireAt||now>new Date(fireAt.getTime()+2*60000))continue;const delivery=await db.notificationDelivery.findUnique({where:{taskId_scheduledAt:{taskId:task.id,scheduledAt:when}}});if(delivery)continue;await db.notificationDelivery.create({data:{taskId:task.id,scheduledAt:when}});for(const sub of subs){try{await webpush.sendNotification({endpoint:sub.endpoint,keys:{p256dh:sub.p256dh,auth:sub.auth}},JSON.stringify({title:task.title,body:(task.reminderMinutes||0)===0?"Starting now":"Starts in "+task.reminderMinutes+" minutes",url:"/tasks?task="+task.id,tag:"task-"+task.id}));sent++}catch(e:any){if(e?.statusCode===404||e?.statusCode===410)await db.pushSubscription.delete({where:{id:sub.id}})}}}
 const recurring=await recurringResponse.json(); return NextResponse.json({sent,checked:tasks.length,recurringCreated:recurring.created||0});
}